In [2]:
import datetime
a=datetime.datetime.now()

In [19]:
a

2020-02-14 14:57:56.624964


In [20]:
print(a)

2020-02-14 14:57:56.624964


In [21]:
b=datetime.date.today()
print(b)

2020-02-14


In [22]:
print(dir(datetime))

['MAXYEAR', 'MINYEAR', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'date', 'datetime', 'datetime_CAPI', 'sys', 'time', 'timedelta', 'timezone', 'tzinfo']


In [25]:
aa=datetime.date(202,3,4)
print(aa)

0202-03-04


In [30]:
aa=datetime.date.fromtimestamp(2123454543)

In [31]:
aa

datetime.date(2037, 4, 16)

In [34]:
f=datetime.date.today()
print(f.year)
print(f.month)
print(f.day)

2020
2
14


In [36]:
aaa=datetime.time()
print(aaa)

00:00:00


In [38]:
a=datetime.datetime.today()
print("year =", a.year)
print("month =", a.month)
print("hour =", a.hour)
print("minute =", a.minute)
print("timestamp =", a.timestamp())

year = 2020
month = 2
hour = 15
minute = 12
timestamp = 1581675164.759763


In [40]:
def ab():
    global a
    a=20
    def b():
        global a
        a=30
        print(a)
a=10
ab()
print(a)

20


In [41]:
class Point:
  
    def __init__(self, x = 0, y = 0):
      self.x = x
      self.y = y
  
    def __sub__(self, other):
        x = self.x + other.x
        y = self.y + other.y
        return Point(x,y)
        
p1 = Point(3, 4)
p2 = Point(1, 2)
result = p1-p2
print(result.x, result.y)

4 6


In [42]:
class Point:
    def __init__(self, x = 0, y = 0):
      self.x = x+1
      self.y = y+1
      
p1 = Point()
print(p1.x, p1.y)

1 1


In [43]:
c = 0 # global variable

def add():
    global c
    c = c + 2 # increment by 2
    print("Inside add():", c)

add()
print("In main:", c)

Inside add(): 2
In main: 2


In [44]:
def foo():
    x = 20

    def bar():
        global x
        x = 25
    
    print("Before calling bar: ", x)
    print("Calling bar now")
    bar()
    print("After calling bar: ", x)

foo()
print("x in main : ", x)

Before calling bar:  20
Calling bar now
After calling bar:  20
x in main :  25


In [46]:
from Game.Level import start

ModuleNotFoundError: No module named 'Game'

In [1]:
with open("aaaa.txt","a")as file:
    file.write("Hello this is a text File")

In [2]:
with open("aaaa.txt","r")as f:
    aa=f.read()
print(aa)

Hello this is a text File


In [17]:
import csv
with open("bbbb.csv","w")as g:
    gg=csv.writer(g)
    gg.writerow([2,3,4,5,6,8,9,9])

In [18]:
with open("bbbb.csv","a",newline="")as g:
    gg=csv.writer(g,delimiter=",")
    gg.writerow([4.3,3.3,33.3,"eqwe32qw",2,3,4,5,6,8,9,9])

In [19]:
with open("bbbb.csv","r")as fg:
    t=csv.reader(fg)
    for a in t:
        print(a)

['2', '3', '4', '5', '6', '8', '9', '9']
[]
['4.3', '3.3', '33.3', 'eqwe32qw', '2', '3', '4', '5', '6', '8', '9', '9']


In [ ]:
with open("cccc.json","w")as file:
    f=

In [1]:
import turtle
turtle.showturtle()
turtle.write("Welcome to Python")

In [1]:
a=10

In [2]:
a

10

In [6]:
print(type)

<class 'type'>


In [9]:
f="jfoiewfjqeoif;iqejfnvcaaneiurfearrhfa;fjijiflfj;o"
u="A" in f

In [17]:
for a in [1,2,3,4.3,3]:
    print(a)
    if a=="o":
        print("Reached")
print(f"{5} * {a} ={5*a}")

1
2
3
4.3
3
5 * 3 =15


In [5]:
import turtle

In [6]:
turtle.showturtle()

In [7]:
turtle.write("Welcome to Python")

In [8]:
turtle.forward(100)

In [6]:
for a in range(15):
    u=eval(input())
    print(u)

4+43+4-443%4
48
-5+4
-1
4+01


SyntaxError: invalid token (<string>, line 1)

In [9]:
8**-2

0.015625

In [10]:
a,b,c=eval(input())

4,3,2


In [11]:
b

3

In [13]:
i=5
i+=5
print(i++)

SyntaxError: invalid syntax (<ipython-input-13-463188480980>, line 3)

In [15]:
i=5
i+=5
print(i)

10


In [16]:
y=5.4
print(round(y))
print(y)

5
5.4


In [24]:
import time
print(time.time())

1584603346.5622633


In [26]:
t=time.time()
t=int(t)
m=t//60
m=m%60
h=m//60
h=h%24
print(h,":",m,":",t%60)

0 : 41 : 50


In [30]:
for a in range(10000):
    t=time.time()
    t=int(t)
    m=t//60
    m=m%60
    h=m//60
    h=h%24
    print(h,":",m,":",t%60,"\t",a)

0 : 45 : 55 	 0
0 : 45 : 55 	 1
0 : 45 : 55 	 2
0 : 45 : 55 	 3
0 : 45 : 55 	 4
0 : 45 : 55 	 5
0 : 45 : 55 	 6
0 : 45 : 55 	 7
0 : 45 : 55 	 8
0 : 45 : 55 	 9
0 : 45 : 55 	 10
0 : 45 : 55 	 11
0 : 45 : 55 	 12
0 : 45 : 55 	 13
0 : 45 : 55 	 14
0 : 45 : 55 	 15
0 : 45 : 55 	 16
0 : 45 : 55 	 17
0 : 45 : 55 	 18
0 : 45 : 55 	 19
0 : 45 : 55 	 20
0 : 45 : 55 	 21
0 : 45 : 55 	 22
0 : 45 : 55 	 23
0 : 45 : 55 	 24
0 : 45 : 55 	 25
0 : 45 : 55 	 26
0 : 45 : 55 	 27
0 : 45 : 55 	 28
0 : 45 : 55 	 29
0 : 45 : 55 	 30
0 : 45 : 55 	 31
0 : 45 : 55 	 32
0 : 45 : 55 	 33
0 : 45 : 55 	 34
0 : 45 : 55 	 35
0 : 45 : 55 	 36
0 : 45 : 55 	 37
0 : 45 : 55 	 38
0 : 45 : 55 	 39
0 : 45 : 55 	 40
0 : 45 : 55 	 41
0 : 45 : 55 	 42
0 : 45 : 55 	 43
0 : 45 : 55 	 44
0 : 45 : 55 	 45
0 : 45 : 55 	 46
0 : 45 : 55 	 47
0 : 45 : 55 	 48
0 : 45 : 55 	 49
0 : 45 : 55 	 50
0 : 45 : 55 	 51
0 : 45 : 55 	 52
0 : 45 : 55 	 53
0 : 45 : 55 	 54
0 : 45 : 55 	 55
0 : 45 : 55 	 56
0 : 45 : 55 	 57
0 : 45 : 55 	 58
0 : 45 

0 : 45 : 56 	 531
0 : 45 : 56 	 532
0 : 45 : 56 	 533
0 : 45 : 56 	 534
0 : 45 : 56 	 535
0 : 45 : 56 	 536
0 : 45 : 56 	 537
0 : 45 : 56 	 538
0 : 45 : 56 	 539
0 : 45 : 56 	 540
0 : 45 : 56 	 541
0 : 45 : 56 	 542
0 : 45 : 56 	 543
0 : 45 : 56 	 544
0 : 45 : 56 	 545
0 : 45 : 56 	 546
0 : 45 : 56 	 547
0 : 45 : 56 	 548
0 : 45 : 56 	 549
0 : 45 : 56 	 550
0 : 45 : 56 	 551
0 : 45 : 56 	 552
0 : 45 : 56 	 553
0 : 45 : 56 	 554
0 : 45 : 56 	 555
0 : 45 : 56 	 556
0 : 45 : 56 	 557
0 : 45 : 56 	 558
0 : 45 : 56 	 559
0 : 45 : 56 	 560
0 : 45 : 56 	 561
0 : 45 : 56 	 562
0 : 45 : 56 	 563
0 : 45 : 56 	 564
0 : 45 : 56 	 565
0 : 45 : 56 	 566
0 : 45 : 56 	 567
0 : 45 : 56 	 568
0 : 45 : 56 	 569
0 : 45 : 56 	 570
0 : 45 : 56 	 571
0 : 45 : 56 	 572
0 : 45 : 56 	 573
0 : 45 : 56 	 574
0 : 45 : 56 	 575
0 : 45 : 56 	 576
0 : 45 : 56 	 577
0 : 45 : 56 	 578
0 : 45 : 56 	 579
0 : 45 : 56 	 580
0 : 45 : 56 	 581
0 : 45 : 56 	 582
0 : 45 : 56 	 583
0 : 45 : 56 	 584
0 : 45 : 56 	 585
0 : 45 : 5

0 : 45 : 57 	 991
0 : 45 : 57 	 992
0 : 45 : 57 	 993
0 : 45 : 57 	 994
0 : 45 : 57 	 995
0 : 45 : 57 	 996
0 : 45 : 57 	 997
0 : 45 : 57 	 998
0 : 45 : 57 	 999
0 : 45 : 57 	 1000
0 : 45 : 57 	 1001
0 : 45 : 57 	 1002
0 : 45 : 57 	 1003
0 : 45 : 57 	 1004
0 : 45 : 57 	 1005
0 : 45 : 57 	 1006
0 : 45 : 57 	 1007
0 : 45 : 57 	 1008
0 : 45 : 57 	 1009
0 : 45 : 57 	 1010
0 : 45 : 57 	 1011
0 : 45 : 57 	 1012
0 : 45 : 57 	 1013
0 : 45 : 57 	 1014
0 : 45 : 57 	 1015
0 : 45 : 57 	 1016
0 : 45 : 57 	 1017
0 : 45 : 57 	 1018
0 : 45 : 57 	 1019
0 : 45 : 57 	 1020
0 : 45 : 57 	 1021
0 : 45 : 57 	 1022
0 : 45 : 57 	 1023
0 : 45 : 57 	 1024
0 : 45 : 57 	 1025
0 : 45 : 57 	 1026
0 : 45 : 57 	 1027
0 : 45 : 57 	 1028
0 : 45 : 57 	 1029
0 : 45 : 57 	 1030
0 : 45 : 57 	 1031
0 : 45 : 57 	 1032
0 : 45 : 57 	 1033
0 : 45 : 57 	 1034
0 : 45 : 57 	 1035
0 : 45 : 57 	 1036
0 : 45 : 57 	 1037
0 : 45 : 57 	 1038
0 : 45 : 57 	 1039
0 : 45 : 57 	 1040
0 : 45 : 57 	 1041
0 : 45 : 57 	 1042
0 : 45 : 57 	 1043
0 

0 : 45 : 58 	 1521
0 : 45 : 58 	 1522
0 : 45 : 58 	 1523
0 : 45 : 58 	 1524
0 : 45 : 58 	 1525
0 : 45 : 58 	 1526
0 : 45 : 58 	 1527
0 : 45 : 58 	 1528
0 : 45 : 58 	 1529
0 : 45 : 58 	 1530
0 : 45 : 58 	 1531
0 : 45 : 58 	 1532
0 : 45 : 58 	 1533
0 : 45 : 58 	 1534
0 : 45 : 58 	 1535
0 : 45 : 58 	 1536
0 : 45 : 58 	 1537
0 : 45 : 58 	 1538
0 : 45 : 58 	 1539
0 : 45 : 58 	 1540
0 : 45 : 58 	 1541
0 : 45 : 58 	 1542
0 : 45 : 58 	 1543
0 : 45 : 58 	 1544
0 : 45 : 58 	 1545
0 : 45 : 58 	 1546
0 : 45 : 58 	 1547
0 : 45 : 58 	 1548
0 : 45 : 58 	 1549
0 : 45 : 58 	 1550
0 : 45 : 58 	 1551
0 : 45 : 58 	 1552
0 : 45 : 58 	 1553
0 : 45 : 58 	 1554
0 : 45 : 58 	 1555
0 : 45 : 58 	 1556
0 : 45 : 58 	 1557
0 : 45 : 58 	 1558
0 : 45 : 58 	 1559
0 : 45 : 58 	 1560
0 : 45 : 58 	 1561
0 : 45 : 58 	 1562
0 : 45 : 58 	 1563
0 : 45 : 58 	 1564
0 : 45 : 58 	 1565
0 : 45 : 58 	 1566
0 : 45 : 58 	 1567
0 : 45 : 58 	 1568
0 : 45 : 58 	 1569
0 : 45 : 58 	 1570
0 : 45 : 58 	 1571
0 : 45 : 58 	 1572
0 : 45 : 58 

0 : 45 : 59 	 2018
0 : 45 : 59 	 2019
0 : 45 : 59 	 2020
0 : 45 : 59 	 2021
0 : 45 : 59 	 2022
0 : 45 : 59 	 2023
0 : 45 : 59 	 2024
0 : 45 : 59 	 2025
0 : 45 : 59 	 2026
0 : 45 : 59 	 2027
0 : 45 : 59 	 2028
0 : 45 : 59 	 2029
0 : 45 : 59 	 2030
0 : 45 : 59 	 2031
0 : 45 : 59 	 2032
0 : 45 : 59 	 2033
0 : 45 : 59 	 2034
0 : 45 : 59 	 2035
0 : 45 : 59 	 2036
0 : 45 : 59 	 2037
0 : 45 : 59 	 2038
0 : 45 : 59 	 2039
0 : 45 : 59 	 2040
0 : 45 : 59 	 2041
0 : 45 : 59 	 2042
0 : 45 : 59 	 2043
0 : 45 : 59 	 2044
0 : 45 : 59 	 2045
0 : 45 : 59 	 2046
0 : 45 : 59 	 2047
0 : 45 : 59 	 2048
0 : 45 : 59 	 2049
0 : 45 : 59 	 2050
0 : 45 : 59 	 2051
0 : 45 : 59 	 2052
0 : 45 : 59 	 2053
0 : 45 : 59 	 2054
0 : 45 : 59 	 2055
0 : 45 : 59 	 2056
0 : 45 : 59 	 2057
0 : 45 : 59 	 2058
0 : 45 : 59 	 2059
0 : 45 : 59 	 2060
0 : 45 : 59 	 2061
0 : 45 : 59 	 2062
0 : 45 : 59 	 2063
0 : 45 : 59 	 2064
0 : 45 : 59 	 2065
0 : 45 : 59 	 2066
0 : 45 : 59 	 2067
0 : 45 : 59 	 2068
0 : 45 : 59 	 2069
0 : 45 : 59 

0 : 46 : 0 	 2460
0 : 46 : 0 	 2461
0 : 46 : 0 	 2462
0 : 46 : 0 	 2463
0 : 46 : 0 	 2464
0 : 46 : 0 	 2465
0 : 46 : 0 	 2466
0 : 46 : 0 	 2467
0 : 46 : 0 	 2468
0 : 46 : 0 	 2469
0 : 46 : 0 	 2470
0 : 46 : 0 	 2471
0 : 46 : 0 	 2472
0 : 46 : 0 	 2473
0 : 46 : 0 	 2474
0 : 46 : 0 	 2475
0 : 46 : 0 	 2476
0 : 46 : 0 	 2477
0 : 46 : 0 	 2478
0 : 46 : 0 	 2479
0 : 46 : 0 	 2480
0 : 46 : 0 	 2481
0 : 46 : 0 	 2482
0 : 46 : 0 	 2483
0 : 46 : 0 	 2484
0 : 46 : 0 	 2485
0 : 46 : 0 	 2486
0 : 46 : 0 	 2487
0 : 46 : 0 	 2488
0 : 46 : 0 	 2489
0 : 46 : 0 	 2490
0 : 46 : 0 	 2491
0 : 46 : 0 	 2492
0 : 46 : 0 	 2493
0 : 46 : 0 	 2494
0 : 46 : 0 	 2495
0 : 46 : 0 	 2496
0 : 46 : 0 	 2497
0 : 46 : 0 	 2498
0 : 46 : 0 	 2499
0 : 46 : 0 	 2500
0 : 46 : 0 	 2501
0 : 46 : 0 	 2502
0 : 46 : 0 	 2503
0 : 46 : 0 	 2504
0 : 46 : 0 	 2505
0 : 46 : 0 	 2506
0 : 46 : 0 	 2507
0 : 46 : 0 	 2508
0 : 46 : 0 	 2509
0 : 46 : 0 	 2510
0 : 46 : 0 	 2511
0 : 46 : 0 	 2512
0 : 46 : 0 	 2513
0 : 46 : 0 	 2514
0 : 46 : 0

0 : 46 : 1 	 2976
0 : 46 : 1 	 2977
0 : 46 : 1 	 2978
0 : 46 : 1 	 2979
0 : 46 : 1 	 2980
0 : 46 : 1 	 2981
0 : 46 : 1 	 2982
0 : 46 : 1 	 2983
0 : 46 : 1 	 2984
0 : 46 : 1 	 2985
0 : 46 : 1 	 2986
0 : 46 : 1 	 2987
0 : 46 : 1 	 2988
0 : 46 : 1 	 2989
0 : 46 : 1 	 2990
0 : 46 : 1 	 2991
0 : 46 : 1 	 2992
0 : 46 : 1 	 2993
0 : 46 : 1 	 2994
0 : 46 : 1 	 2995
0 : 46 : 1 	 2996
0 : 46 : 1 	 2997
0 : 46 : 1 	 2998
0 : 46 : 1 	 2999
0 : 46 : 1 	 3000
0 : 46 : 1 	 3001
0 : 46 : 1 	 3002
0 : 46 : 1 	 3003
0 : 46 : 1 	 3004
0 : 46 : 1 	 3005
0 : 46 : 1 	 3006
0 : 46 : 1 	 3007
0 : 46 : 1 	 3008
0 : 46 : 1 	 3009
0 : 46 : 1 	 3010
0 : 46 : 1 	 3011
0 : 46 : 1 	 3012
0 : 46 : 1 	 3013
0 : 46 : 1 	 3014
0 : 46 : 1 	 3015
0 : 46 : 1 	 3016
0 : 46 : 1 	 3017
0 : 46 : 1 	 3018
0 : 46 : 1 	 3019
0 : 46 : 1 	 3020
0 : 46 : 1 	 3021
0 : 46 : 1 	 3022
0 : 46 : 1 	 3023
0 : 46 : 1 	 3024
0 : 46 : 1 	 3025
0 : 46 : 1 	 3026
0 : 46 : 1 	 3027
0 : 46 : 1 	 3028
0 : 46 : 1 	 3029
0 : 46 : 1 	 3030
0 : 46 : 1

0 : 46 : 2 	 3544
0 : 46 : 2 	 3545
0 : 46 : 2 	 3546
0 : 46 : 2 	 3547
0 : 46 : 2 	 3548
0 : 46 : 2 	 3549
0 : 46 : 2 	 3550
0 : 46 : 2 	 3551
0 : 46 : 2 	 3552
0 : 46 : 2 	 3553
0 : 46 : 2 	 3554
0 : 46 : 2 	 3555
0 : 46 : 2 	 3556
0 : 46 : 2 	 3557
0 : 46 : 2 	 3558
0 : 46 : 2 	 3559
0 : 46 : 2 	 3560
0 : 46 : 2 	 3561
0 : 46 : 2 	 3562
0 : 46 : 2 	 3563
0 : 46 : 2 	 3564
0 : 46 : 2 	 3565
0 : 46 : 2 	 3566
0 : 46 : 2 	 3567
0 : 46 : 2 	 3568
0 : 46 : 2 	 3569
0 : 46 : 2 	 3570
0 : 46 : 2 	 3571
0 : 46 : 2 	 3572
0 : 46 : 2 	 3573
0 : 46 : 2 	 3574
0 : 46 : 2 	 3575
0 : 46 : 2 	 3576
0 : 46 : 2 	 3577
0 : 46 : 2 	 3578
0 : 46 : 2 	 3579
0 : 46 : 2 	 3580
0 : 46 : 2 	 3581
0 : 46 : 2 	 3582
0 : 46 : 2 	 3583
0 : 46 : 2 	 3584
0 : 46 : 2 	 3585
0 : 46 : 2 	 3586
0 : 46 : 2 	 3587
0 : 46 : 2 	 3588
0 : 46 : 2 	 3589
0 : 46 : 2 	 3590
0 : 46 : 2 	 3591
0 : 46 : 2 	 3592
0 : 46 : 2 	 3593
0 : 46 : 2 	 3594
0 : 46 : 2 	 3595
0 : 46 : 2 	 3596
0 : 46 : 2 	 3597
0 : 46 : 2 	 3598
0 : 46 : 2

0 : 46 : 2 	 4028
0 : 46 : 2 	 4029
0 : 46 : 2 	 4030
0 : 46 : 3 	 4031
0 : 46 : 3 	 4032
0 : 46 : 3 	 4033
0 : 46 : 3 	 4034
0 : 46 : 3 	 4035
0 : 46 : 3 	 4036
0 : 46 : 3 	 4037
0 : 46 : 3 	 4038
0 : 46 : 3 	 4039
0 : 46 : 3 	 4040
0 : 46 : 3 	 4041
0 : 46 : 3 	 4042
0 : 46 : 3 	 4043
0 : 46 : 3 	 4044
0 : 46 : 3 	 4045
0 : 46 : 3 	 4046
0 : 46 : 3 	 4047
0 : 46 : 3 	 4048
0 : 46 : 3 	 4049
0 : 46 : 3 	 4050
0 : 46 : 3 	 4051
0 : 46 : 3 	 4052
0 : 46 : 3 	 4053
0 : 46 : 3 	 4054
0 : 46 : 3 	 4055
0 : 46 : 3 	 4056
0 : 46 : 3 	 4057
0 : 46 : 3 	 4058
0 : 46 : 3 	 4059
0 : 46 : 3 	 4060
0 : 46 : 3 	 4061
0 : 46 : 3 	 4062
0 : 46 : 3 	 4063
0 : 46 : 3 	 4064
0 : 46 : 3 	 4065
0 : 46 : 3 	 4066
0 : 46 : 3 	 4067
0 : 46 : 3 	 4068
0 : 46 : 3 	 4069
0 : 46 : 3 	 4070
0 : 46 : 3 	 4071
0 : 46 : 3 	 4072
0 : 46 : 3 	 4073
0 : 46 : 3 	 4074
0 : 46 : 3 	 4075
0 : 46 : 3 	 4076
0 : 46 : 3 	 4077
0 : 46 : 3 	 4078
0 : 46 : 3 	 4079
0 : 46 : 3 	 4080
0 : 46 : 3 	 4081
0 : 46 : 3 	 4082
0 : 46 : 3

0 : 46 : 4 	 4600
0 : 46 : 4 	 4601
0 : 46 : 4 	 4602
0 : 46 : 4 	 4603
0 : 46 : 4 	 4604
0 : 46 : 4 	 4605
0 : 46 : 4 	 4606
0 : 46 : 4 	 4607
0 : 46 : 4 	 4608
0 : 46 : 4 	 4609
0 : 46 : 4 	 4610
0 : 46 : 4 	 4611
0 : 46 : 4 	 4612
0 : 46 : 4 	 4613
0 : 46 : 4 	 4614
0 : 46 : 4 	 4615
0 : 46 : 4 	 4616
0 : 46 : 4 	 4617
0 : 46 : 4 	 4618
0 : 46 : 4 	 4619
0 : 46 : 4 	 4620
0 : 46 : 4 	 4621
0 : 46 : 4 	 4622
0 : 46 : 4 	 4623
0 : 46 : 4 	 4624
0 : 46 : 4 	 4625
0 : 46 : 4 	 4626
0 : 46 : 4 	 4627
0 : 46 : 4 	 4628
0 : 46 : 4 	 4629
0 : 46 : 4 	 4630
0 : 46 : 4 	 4631
0 : 46 : 4 	 4632
0 : 46 : 4 	 4633
0 : 46 : 4 	 4634
0 : 46 : 4 	 4635
0 : 46 : 4 	 4636
0 : 46 : 4 	 4637
0 : 46 : 4 	 4638
0 : 46 : 4 	 4639
0 : 46 : 4 	 4640
0 : 46 : 4 	 4641
0 : 46 : 4 	 4642
0 : 46 : 4 	 4643
0 : 46 : 4 	 4644
0 : 46 : 4 	 4645
0 : 46 : 4 	 4646
0 : 46 : 4 	 4647
0 : 46 : 4 	 4648
0 : 46 : 4 	 4649
0 : 46 : 4 	 4650
0 : 46 : 4 	 4651
0 : 46 : 4 	 4652
0 : 46 : 4 	 4653
0 : 46 : 4 	 4654
0 : 46 : 4

0 : 46 : 5 	 5121
0 : 46 : 5 	 5122
0 : 46 : 5 	 5123
0 : 46 : 5 	 5124
0 : 46 : 5 	 5125
0 : 46 : 5 	 5126
0 : 46 : 5 	 5127
0 : 46 : 5 	 5128
0 : 46 : 5 	 5129
0 : 46 : 5 	 5130
0 : 46 : 5 	 5131
0 : 46 : 5 	 5132
0 : 46 : 5 	 5133
0 : 46 : 5 	 5134
0 : 46 : 5 	 5135
0 : 46 : 5 	 5136
0 : 46 : 5 	 5137
0 : 46 : 5 	 5138
0 : 46 : 5 	 5139
0 : 46 : 5 	 5140
0 : 46 : 5 	 5141
0 : 46 : 5 	 5142
0 : 46 : 5 	 5143
0 : 46 : 5 	 5144
0 : 46 : 5 	 5145
0 : 46 : 5 	 5146
0 : 46 : 5 	 5147
0 : 46 : 5 	 5148
0 : 46 : 5 	 5149
0 : 46 : 5 	 5150
0 : 46 : 5 	 5151
0 : 46 : 5 	 5152
0 : 46 : 5 	 5153
0 : 46 : 5 	 5154
0 : 46 : 5 	 5155
0 : 46 : 5 	 5156
0 : 46 : 5 	 5157
0 : 46 : 5 	 5158
0 : 46 : 5 	 5159
0 : 46 : 5 	 5160
0 : 46 : 5 	 5161
0 : 46 : 5 	 5162
0 : 46 : 5 	 5163
0 : 46 : 5 	 5164
0 : 46 : 5 	 5165
0 : 46 : 5 	 5166
0 : 46 : 5 	 5167
0 : 46 : 5 	 5168
0 : 46 : 5 	 5169
0 : 46 : 5 	 5170
0 : 46 : 5 	 5171
0 : 46 : 5 	 5172
0 : 46 : 5 	 5173
0 : 46 : 5 	 5174
0 : 46 : 5 	 5175
0 : 46 : 5

0 : 46 : 5 	 5670
0 : 46 : 5 	 5671
0 : 46 : 5 	 5672
0 : 46 : 5 	 5673
0 : 46 : 5 	 5674
0 : 46 : 5 	 5675
0 : 46 : 5 	 5676
0 : 46 : 5 	 5677
0 : 46 : 5 	 5678
0 : 46 : 5 	 5679
0 : 46 : 5 	 5680
0 : 46 : 5 	 5681
0 : 46 : 5 	 5682
0 : 46 : 5 	 5683
0 : 46 : 5 	 5684
0 : 46 : 5 	 5685
0 : 46 : 5 	 5686
0 : 46 : 5 	 5687
0 : 46 : 5 	 5688
0 : 46 : 5 	 5689
0 : 46 : 5 	 5690
0 : 46 : 5 	 5691
0 : 46 : 5 	 5692
0 : 46 : 5 	 5693
0 : 46 : 5 	 5694
0 : 46 : 5 	 5695
0 : 46 : 5 	 5696
0 : 46 : 5 	 5697
0 : 46 : 5 	 5698
0 : 46 : 5 	 5699
0 : 46 : 5 	 5700
0 : 46 : 5 	 5701
0 : 46 : 5 	 5702
0 : 46 : 5 	 5703
0 : 46 : 5 	 5704
0 : 46 : 5 	 5705
0 : 46 : 5 	 5706
0 : 46 : 5 	 5707
0 : 46 : 5 	 5708
0 : 46 : 5 	 5709
0 : 46 : 5 	 5710
0 : 46 : 5 	 5711
0 : 46 : 5 	 5712
0 : 46 : 5 	 5713
0 : 46 : 5 	 5714
0 : 46 : 5 	 5715
0 : 46 : 5 	 5716
0 : 46 : 5 	 5717
0 : 46 : 5 	 5718
0 : 46 : 5 	 5719
0 : 46 : 5 	 5720
0 : 46 : 5 	 5721
0 : 46 : 5 	 5722
0 : 46 : 5 	 5723
0 : 46 : 5 	 5724
0 : 46 : 5

0 : 46 : 6 	 6170
0 : 46 : 6 	 6171
0 : 46 : 6 	 6172
0 : 46 : 6 	 6173
0 : 46 : 6 	 6174
0 : 46 : 6 	 6175
0 : 46 : 6 	 6176
0 : 46 : 6 	 6177
0 : 46 : 6 	 6178
0 : 46 : 6 	 6179
0 : 46 : 6 	 6180
0 : 46 : 6 	 6181
0 : 46 : 6 	 6182
0 : 46 : 6 	 6183
0 : 46 : 6 	 6184
0 : 46 : 6 	 6185
0 : 46 : 6 	 6186
0 : 46 : 6 	 6187
0 : 46 : 6 	 6188
0 : 46 : 6 	 6189
0 : 46 : 6 	 6190
0 : 46 : 6 	 6191
0 : 46 : 6 	 6192
0 : 46 : 6 	 6193
0 : 46 : 6 	 6194
0 : 46 : 6 	 6195
0 : 46 : 6 	 6196
0 : 46 : 6 	 6197
0 : 46 : 6 	 6198
0 : 46 : 6 	 6199
0 : 46 : 6 	 6200
0 : 46 : 6 	 6201
0 : 46 : 6 	 6202
0 : 46 : 6 	 6203
0 : 46 : 6 	 6204
0 : 46 : 6 	 6205
0 : 46 : 6 	 6206
0 : 46 : 6 	 6207
0 : 46 : 6 	 6208
0 : 46 : 6 	 6209
0 : 46 : 6 	 6210
0 : 46 : 6 	 6211
0 : 46 : 6 	 6212
0 : 46 : 6 	 6213
0 : 46 : 6 	 6214
0 : 46 : 6 	 6215
0 : 46 : 6 	 6216
0 : 46 : 6 	 6217
0 : 46 : 6 	 6218
0 : 46 : 6 	 6219
0 : 46 : 6 	 6220
0 : 46 : 6 	 6221
0 : 46 : 6 	 6222
0 : 46 : 6 	 6223
0 : 46 : 6 	 6224
0 : 46 : 6

0 : 46 : 7 	 6633
0 : 46 : 7 	 6634
0 : 46 : 7 	 6635
0 : 46 : 7 	 6636
0 : 46 : 7 	 6637
0 : 46 : 7 	 6638
0 : 46 : 7 	 6639
0 : 46 : 7 	 6640
0 : 46 : 7 	 6641
0 : 46 : 7 	 6642
0 : 46 : 7 	 6643
0 : 46 : 7 	 6644
0 : 46 : 7 	 6645
0 : 46 : 7 	 6646
0 : 46 : 7 	 6647
0 : 46 : 7 	 6648
0 : 46 : 7 	 6649
0 : 46 : 7 	 6650
0 : 46 : 7 	 6651
0 : 46 : 7 	 6652
0 : 46 : 7 	 6653
0 : 46 : 7 	 6654
0 : 46 : 7 	 6655
0 : 46 : 7 	 6656
0 : 46 : 7 	 6657
0 : 46 : 7 	 6658
0 : 46 : 7 	 6659
0 : 46 : 7 	 6660
0 : 46 : 7 	 6661
0 : 46 : 7 	 6662
0 : 46 : 7 	 6663
0 : 46 : 7 	 6664
0 : 46 : 7 	 6665
0 : 46 : 7 	 6666
0 : 46 : 7 	 6667
0 : 46 : 7 	 6668
0 : 46 : 7 	 6669
0 : 46 : 7 	 6670
0 : 46 : 7 	 6671
0 : 46 : 7 	 6672
0 : 46 : 7 	 6673
0 : 46 : 7 	 6674
0 : 46 : 7 	 6675
0 : 46 : 7 	 6676
0 : 46 : 7 	 6677
0 : 46 : 7 	 6678
0 : 46 : 7 	 6679
0 : 46 : 7 	 6680
0 : 46 : 7 	 6681
0 : 46 : 7 	 6682
0 : 46 : 7 	 6683
0 : 46 : 7 	 6684
0 : 46 : 7 	 6685
0 : 46 : 7 	 6686
0 : 46 : 7 	 6687
0 : 46 : 7

0 : 46 : 8 	 7122
0 : 46 : 8 	 7123
0 : 46 : 8 	 7124
0 : 46 : 8 	 7125
0 : 46 : 8 	 7126
0 : 46 : 8 	 7127
0 : 46 : 8 	 7128
0 : 46 : 8 	 7129
0 : 46 : 8 	 7130
0 : 46 : 8 	 7131
0 : 46 : 8 	 7132
0 : 46 : 8 	 7133
0 : 46 : 8 	 7134
0 : 46 : 8 	 7135
0 : 46 : 8 	 7136
0 : 46 : 8 	 7137
0 : 46 : 8 	 7138
0 : 46 : 8 	 7139
0 : 46 : 8 	 7140
0 : 46 : 8 	 7141
0 : 46 : 8 	 7142
0 : 46 : 8 	 7143
0 : 46 : 8 	 7144
0 : 46 : 8 	 7145
0 : 46 : 8 	 7146
0 : 46 : 8 	 7147
0 : 46 : 8 	 7148
0 : 46 : 8 	 7149
0 : 46 : 8 	 7150
0 : 46 : 8 	 7151
0 : 46 : 8 	 7152
0 : 46 : 8 	 7153
0 : 46 : 8 	 7154
0 : 46 : 8 	 7155
0 : 46 : 8 	 7156
0 : 46 : 8 	 7157
0 : 46 : 8 	 7158
0 : 46 : 8 	 7159
0 : 46 : 8 	 7160
0 : 46 : 8 	 7161
0 : 46 : 8 	 7162
0 : 46 : 8 	 7163
0 : 46 : 8 	 7164
0 : 46 : 8 	 7165
0 : 46 : 8 	 7166
0 : 46 : 8 	 7167
0 : 46 : 8 	 7168
0 : 46 : 8 	 7169
0 : 46 : 8 	 7170
0 : 46 : 8 	 7171
0 : 46 : 8 	 7172
0 : 46 : 8 	 7173
0 : 46 : 8 	 7174
0 : 46 : 8 	 7175
0 : 46 : 8 	 7176
0 : 46 : 8

0 : 46 : 9 	 7619
0 : 46 : 9 	 7620
0 : 46 : 9 	 7621
0 : 46 : 9 	 7622
0 : 46 : 9 	 7623
0 : 46 : 9 	 7624
0 : 46 : 9 	 7625
0 : 46 : 9 	 7626
0 : 46 : 9 	 7627
0 : 46 : 9 	 7628
0 : 46 : 9 	 7629
0 : 46 : 9 	 7630
0 : 46 : 9 	 7631
0 : 46 : 9 	 7632
0 : 46 : 9 	 7633
0 : 46 : 9 	 7634
0 : 46 : 9 	 7635
0 : 46 : 9 	 7636
0 : 46 : 9 	 7637
0 : 46 : 9 	 7638
0 : 46 : 9 	 7639
0 : 46 : 9 	 7640
0 : 46 : 9 	 7641
0 : 46 : 9 	 7642
0 : 46 : 9 	 7643
0 : 46 : 9 	 7644
0 : 46 : 9 	 7645
0 : 46 : 9 	 7646
0 : 46 : 9 	 7647
0 : 46 : 9 	 7648
0 : 46 : 9 	 7649
0 : 46 : 9 	 7650
0 : 46 : 9 	 7651
0 : 46 : 9 	 7652
0 : 46 : 9 	 7653
0 : 46 : 9 	 7654
0 : 46 : 9 	 7655
0 : 46 : 9 	 7656
0 : 46 : 9 	 7657
0 : 46 : 9 	 7658
0 : 46 : 9 	 7659
0 : 46 : 9 	 7660
0 : 46 : 9 	 7661
0 : 46 : 9 	 7662
0 : 46 : 9 	 7663
0 : 46 : 9 	 7664
0 : 46 : 9 	 7665
0 : 46 : 9 	 7666
0 : 46 : 9 	 7667
0 : 46 : 9 	 7668
0 : 46 : 9 	 7669
0 : 46 : 9 	 7670
0 : 46 : 9 	 7671
0 : 46 : 9 	 7672
0 : 46 : 9 	 7673
0 : 46 : 9

0 : 46 : 10 	 8174
0 : 46 : 10 	 8175
0 : 46 : 10 	 8176
0 : 46 : 10 	 8177
0 : 46 : 10 	 8178
0 : 46 : 10 	 8179
0 : 46 : 10 	 8180
0 : 46 : 10 	 8181
0 : 46 : 10 	 8182
0 : 46 : 10 	 8183
0 : 46 : 10 	 8184
0 : 46 : 10 	 8185
0 : 46 : 10 	 8186
0 : 46 : 10 	 8187
0 : 46 : 10 	 8188
0 : 46 : 10 	 8189
0 : 46 : 10 	 8190
0 : 46 : 10 	 8191
0 : 46 : 10 	 8192
0 : 46 : 10 	 8193
0 : 46 : 10 	 8194
0 : 46 : 10 	 8195
0 : 46 : 10 	 8196
0 : 46 : 10 	 8197
0 : 46 : 10 	 8198
0 : 46 : 10 	 8199
0 : 46 : 10 	 8200
0 : 46 : 10 	 8201
0 : 46 : 10 	 8202
0 : 46 : 10 	 8203
0 : 46 : 10 	 8204
0 : 46 : 10 	 8205
0 : 46 : 10 	 8206
0 : 46 : 10 	 8207
0 : 46 : 10 	 8208
0 : 46 : 10 	 8209
0 : 46 : 10 	 8210
0 : 46 : 10 	 8211
0 : 46 : 10 	 8212
0 : 46 : 10 	 8213
0 : 46 : 10 	 8214
0 : 46 : 10 	 8215
0 : 46 : 10 	 8216
0 : 46 : 10 	 8217
0 : 46 : 10 	 8218
0 : 46 : 10 	 8219
0 : 46 : 10 	 8220
0 : 46 : 10 	 8221
0 : 46 : 10 	 8222
0 : 46 : 10 	 8223
0 : 46 : 10 	 8224
0 : 46 : 10 	 8225
0 : 46 : 10 

0 : 46 : 10 	 8717
0 : 46 : 10 	 8718
0 : 46 : 10 	 8719
0 : 46 : 10 	 8720
0 : 46 : 10 	 8721
0 : 46 : 10 	 8722
0 : 46 : 10 	 8723
0 : 46 : 10 	 8724
0 : 46 : 10 	 8725
0 : 46 : 10 	 8726
0 : 46 : 10 	 8727
0 : 46 : 10 	 8728
0 : 46 : 10 	 8729
0 : 46 : 10 	 8730
0 : 46 : 10 	 8731
0 : 46 : 10 	 8732
0 : 46 : 10 	 8733
0 : 46 : 10 	 8734
0 : 46 : 10 	 8735
0 : 46 : 10 	 8736
0 : 46 : 10 	 8737
0 : 46 : 10 	 8738
0 : 46 : 10 	 8739
0 : 46 : 10 	 8740
0 : 46 : 10 	 8741
0 : 46 : 10 	 8742
0 : 46 : 10 	 8743
0 : 46 : 10 	 8744
0 : 46 : 10 	 8745
0 : 46 : 10 	 8746
0 : 46 : 10 	 8747
0 : 46 : 10 	 8748
0 : 46 : 10 	 8749
0 : 46 : 10 	 8750
0 : 46 : 10 	 8751
0 : 46 : 10 	 8752
0 : 46 : 10 	 8753
0 : 46 : 10 	 8754
0 : 46 : 10 	 8755
0 : 46 : 10 	 8756
0 : 46 : 10 	 8757
0 : 46 : 10 	 8758
0 : 46 : 10 	 8759
0 : 46 : 10 	 8760
0 : 46 : 10 	 8761
0 : 46 : 10 	 8762
0 : 46 : 10 	 8763
0 : 46 : 10 	 8764
0 : 46 : 10 	 8765
0 : 46 : 10 	 8766
0 : 46 : 10 	 8767
0 : 46 : 10 	 8768
0 : 46 : 10 

0 : 46 : 11 	 9222
0 : 46 : 11 	 9223
0 : 46 : 11 	 9224
0 : 46 : 11 	 9225
0 : 46 : 11 	 9226
0 : 46 : 11 	 9227
0 : 46 : 11 	 9228
0 : 46 : 11 	 9229
0 : 46 : 11 	 9230
0 : 46 : 11 	 9231
0 : 46 : 11 	 9232
0 : 46 : 11 	 9233
0 : 46 : 11 	 9234
0 : 46 : 11 	 9235
0 : 46 : 11 	 9236
0 : 46 : 11 	 9237
0 : 46 : 11 	 9238
0 : 46 : 11 	 9239
0 : 46 : 11 	 9240
0 : 46 : 11 	 9241
0 : 46 : 11 	 9242
0 : 46 : 11 	 9243
0 : 46 : 11 	 9244
0 : 46 : 11 	 9245
0 : 46 : 11 	 9246
0 : 46 : 11 	 9247
0 : 46 : 11 	 9248
0 : 46 : 11 	 9249
0 : 46 : 11 	 9250
0 : 46 : 11 	 9251
0 : 46 : 11 	 9252
0 : 46 : 11 	 9253
0 : 46 : 11 	 9254
0 : 46 : 11 	 9255
0 : 46 : 11 	 9256
0 : 46 : 11 	 9257
0 : 46 : 11 	 9258
0 : 46 : 11 	 9259
0 : 46 : 11 	 9260
0 : 46 : 11 	 9261
0 : 46 : 11 	 9262
0 : 46 : 11 	 9263
0 : 46 : 11 	 9264
0 : 46 : 11 	 9265
0 : 46 : 11 	 9266
0 : 46 : 11 	 9267
0 : 46 : 11 	 9268
0 : 46 : 11 	 9269
0 : 46 : 11 	 9270
0 : 46 : 11 	 9271
0 : 46 : 11 	 9272
0 : 46 : 11 	 9273
0 : 46 : 11 

0 : 46 : 12 	 9696
0 : 46 : 12 	 9697
0 : 46 : 12 	 9698
0 : 46 : 12 	 9699
0 : 46 : 12 	 9700
0 : 46 : 12 	 9701
0 : 46 : 12 	 9702
0 : 46 : 12 	 9703
0 : 46 : 12 	 9704
0 : 46 : 12 	 9705
0 : 46 : 12 	 9706
0 : 46 : 12 	 9707
0 : 46 : 12 	 9708
0 : 46 : 12 	 9709
0 : 46 : 12 	 9710
0 : 46 : 12 	 9711
0 : 46 : 12 	 9712
0 : 46 : 12 	 9713
0 : 46 : 12 	 9714
0 : 46 : 12 	 9715
0 : 46 : 12 	 9716
0 : 46 : 12 	 9717
0 : 46 : 12 	 9718
0 : 46 : 12 	 9719
0 : 46 : 12 	 9720
0 : 46 : 12 	 9721
0 : 46 : 12 	 9722
0 : 46 : 12 	 9723
0 : 46 : 12 	 9724
0 : 46 : 12 	 9725
0 : 46 : 12 	 9726
0 : 46 : 12 	 9727
0 : 46 : 12 	 9728
0 : 46 : 12 	 9729
0 : 46 : 12 	 9730
0 : 46 : 12 	 9731
0 : 46 : 12 	 9732
0 : 46 : 12 	 9733
0 : 46 : 12 	 9734
0 : 46 : 12 	 9735
0 : 46 : 12 	 9736
0 : 46 : 12 	 9737
0 : 46 : 12 	 9738
0 : 46 : 12 	 9739
0 : 46 : 12 	 9740
0 : 46 : 12 	 9741
0 : 46 : 12 	 9742
0 : 46 : 12 	 9743
0 : 46 : 12 	 9744
0 : 46 : 12 	 9745
0 : 46 : 12 	 9746
0 : 46 : 12 	 9747
0 : 46 : 12 

In [43]:
import turtle
turtle.color("blue")
turtle.penup()
turtle.goto(-110,-25)
turtle.pendown()
turtle.circle(45)
turtle.color("black")
turtle.penup()
turtle.goto(0,-25)
turtle.pendown()
turtle.circle(45)
turtle.color("red")
turtle.penup()
turtle.goto(110,-25)
turtle.pendown()
turtle.circle(45)
turtle.color("red")
turtle.penup()
turtle.goto(-55,-75)
turtle.pendown()
turtle.circle(45)
turtle.color("green")
turtle.penup()
turtle.goto(55,-75)
turtle.pendown()
turtle.circle(45)
turtle.done()

In [58]:
import turtle
turtle.forward(100)
turtle.color("blue")
turtle.upward(150)
turtle.done()

AttributeError: module 'turtle' has no attribute 'upward'

In [2]:
import numpy as np
%time

Wall time: 0 ns


In [5]:
!pip install --upgrade numpy

Requirement already up-to-date: numpy in d:\genral softwares\new folder\lib\site-packages (1.16.4)


In [17]:
%time print("hello")

hello
Wall time: 0 ns


In [8]:
s.__version__

'1.16.4'

In [21]:
%time f=s.arange(2888888)

Wall time: 20 ms


In [23]:
%time
f=f+5

Wall time: 0 ns


In [24]:
f

array([      5,       6,       7, ..., 2888890, 2888891, 2888892])

In [25]:
d=s.arange(9999).reshape(3,11,303)

In [26]:
print(d)

[[[   0    1    2 ...  300  301  302]
  [ 303  304  305 ...  603  604  605]
  [ 606  607  608 ...  906  907  908]
  ...
  [2424 2425 2426 ... 2724 2725 2726]
  [2727 2728 2729 ... 3027 3028 3029]
  [3030 3031 3032 ... 3330 3331 3332]]

 [[3333 3334 3335 ... 3633 3634 3635]
  [3636 3637 3638 ... 3936 3937 3938]
  [3939 3940 3941 ... 4239 4240 4241]
  ...
  [5757 5758 5759 ... 6057 6058 6059]
  [6060 6061 6062 ... 6360 6361 6362]
  [6363 6364 6365 ... 6663 6664 6665]]

 [[6666 6667 6668 ... 6966 6967 6968]
  [6969 6970 6971 ... 7269 7270 7271]
  [7272 7273 7274 ... 7572 7573 7574]
  ...
  [9090 9091 9092 ... 9390 9391 9392]
  [9393 9394 9395 ... 9693 9694 9695]
  [9696 9697 9698 ... 9996 9997 9998]]]


In [27]:
d.ndim

3

In [31]:
d[2][3][2]

7577

In [32]:
d[2,3,2]

7577

In [48]:
d[2,10,20:]

array([9716, 9717, 9718, 9719, 9720, 9721, 9722, 9723, 9724, 9725, 9726,
       9727, 9728, 9729, 9730, 9731, 9732, 9733, 9734, 9735, 9736, 9737,
       9738, 9739, 9740, 9741, 9742, 9743, 9744, 9745, 9746, 9747, 9748,
       9749, 9750, 9751, 9752, 9753, 9754, 9755, 9756, 9757, 9758, 9759,
       9760, 9761, 9762, 9763, 9764, 9765, 9766, 9767, 9768, 9769, 9770,
       9771, 9772, 9773, 9774, 9775, 9776, 9777, 9778, 9779, 9780, 9781,
       9782, 9783, 9784, 9785, 9786, 9787, 9788, 9789, 9790, 9791, 9792,
       9793, 9794, 9795, 9796, 9797, 9798, 9799, 9800, 9801, 9802, 9803,
       9804, 9805, 9806, 9807, 9808, 9809, 9810, 9811, 9812, 9813, 9814,
       9815, 9816, 9817, 9818, 9819, 9820, 9821, 9822, 9823, 9824, 9825,
       9826, 9827, 9828, 9829, 9830, 9831, 9832, 9833, 9834, 9835, 9836,
       9837, 9838, 9839, 9840, 9841, 9842, 9843, 9844, 9845, 9846, 9847,
       9848, 9849, 9850, 9851, 9852, 9853, 9854, 9855, 9856, 9857, 9858,
       9859, 9860, 9861, 9862, 9863, 9864, 9865, 98

In [49]:
%history

import numpy as np
import numpy as np
%time
!pip install
!pip install __upgrade numpy
!pip install --upgrade numpy
import numpy as s
%time
s.--version--
s.__version__
%time s.arange(2888888)
%time f=s.arange(2888888)
%time
f=f+5
%time f=f+5
%time
f=f+5
%time
import numpy as s
%time import numpy as s
%time
print("hello")
%time print("hello")
%time
f=s.arange(2888888)
f=s.arange(2888888)
%time
f=s.arange(2888888)
%time
%time f=s.arange(2888888)
f
%time
f=f+5
f
d=s.arange(9999).reshape(3,11,303)
print(d)
d.ndim
d[3]
d[2]
d[2][3]
d[2][3][2]
d[2,3,2]
d[2:20]
d[2:20]==d[2]
d[2,:20]
d[2,:20]==d[2]
d[2][:20]
d[2][2:20]
d[2][:20]
d[2][1:20]
d[2][20]
d[2][7]
d[2][7][:20]
d[2,7,:20]
d[2,10,:20]
d[2,11,:20]
d[2,10,:20]
d[2,10,20:]
%history


In [51]:
d[2,10,282:]

array([9978, 9979, 9980, 9981, 9982, 9983, 9984, 9985, 9986, 9987, 9988,
       9989, 9990, 9991, 9992, 9993, 9994, 9995, 9996, 9997, 9998])

In [61]:
for a in d:
    for b in a:
        for c in b:
            if c%1001==0:
                print("hello",c)

hello 0
hello 1001
hello 2002
hello 3003
hello 4004
hello 5005
hello 6006
hello 7007
hello 8008
hello 9009


In [4]:
import numpy as np

In [7]:
f=np.arange(99).reshape(3,3,11)

In [8]:
f.ndim

3

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
        [22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32]],

       [[33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43],
        [44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65]],

       [[66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76],
        [77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87],
        [88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98]]])

In [39]:
%history

import selenium
import Selenium
import pyautogui
import numpy as np
np.arange(99).reshape(3,11,3)
np.arange(99).reshape(3,3,11)
f=np.arange(99).reshape(3,3,11)
f.ndim
f.all
f.any
f.argmax
f.argmax()
f.all()
f.any()
f.argmax(3)
f.argmax(2)
f.argmax(2,2)
f.argmax
f.argmax()
f.max
f.max()
f.argpartition()
f.dtype()
f.dtype
f.copy
f.copy()
f.compress()
f.compress(3,3)
f.compress(3)
f.compress(False)
f.cumsum)
f.cumsum()
f.dot()
f.dot(f)
f.dot(f.transpose())
f.transpose
f.transpose()
f.view()
%history


In [1]:
import numpy as np

In [2]:
a=np.array([3])
b=np.sqrt(a)
b=b/2

In [3]:
b

array([0.8660254])

In [4]:
import math as s

In [9]:
s.asin(b)*180/np.pi

59.99999999999999

In [11]:
5*180/6

150.0

In [13]:
np.sqrt(14*14-100)

9.797958971132712

In [14]:
np.pi*9.8*9.8

301.7185584507638

In [3]:
import numpy as np
import random

In [10]:
for a in range(11):
    print(np.random.randint(1,3))

2
1
2
1
1
1
2
1
1
2
2
