In [1]:
import numpy as f

In [2]:
matrix=f.array([[1,2,3,4],[4,3,2,1]])

In [3]:
matrix

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [4]:
mat=f.arange(1,21).reshape(5,4)

In [5]:
rix=f.arange(2,22).reshape(5,4)

In [6]:
mat+rix

array([[ 3,  5,  7,  9],
       [11, 13, 15, 17],
       [19, 21, 23, 25],
       [27, 29, 31, 33],
       [35, 37, 39, 41]])

In [7]:
rix

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [8]:
f.transpose(rix)

array([[ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19],
       [ 4,  8, 12, 16, 20],
       [ 5,  9, 13, 17, 21]])

In [9]:
print(mat)
print(rix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [10]:
rix=rix.transpose()

In [11]:
mat@rix

array([[  40,   80,  120,  160,  200],
       [  96,  200,  304,  408,  512],
       [ 152,  320,  488,  656,  824],
       [ 208,  440,  672,  904, 1136],
       [ 264,  560,  856, 1152, 1448]])

In [12]:
rix.dot(mat)

array([[610, 660, 710, 760],
       [655, 710, 765, 820],
       [700, 760, 820, 880],
       [745, 810, 875, 940]])

In [16]:
ff=mat.dot(rix)
ff

array([[  40,   80,  120,  160,  200],
       [  96,  200,  304,  408,  512],
       [ 152,  320,  488,  656,  824],
       [ 208,  440,  672,  904, 1136],
       [ 264,  560,  856, 1152, 1448]])

In [22]:
ff[ff<600]=5
ff

array([[   5,    5,    5,    5,    5],
       [   5,    5,    5,    5,    5],
       [   5,    5,    5,  656,  824],
       [   5,    5,  672,  904, 1136],
       [   5,    5,  856, 1152, 1448]])

In [30]:
ff==656

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [33]:
ff

array([[   5,    5,    5,    5,    5],
       [   5,    5,    5,    5,    5],
       [   5,    5,    5,  656,  824],
       [   5,    5,  672,  904, 1136],
       [   5,    5,  856, 1152, 1448]])

In [37]:
ff.swapaxes(1,0)

array([[   5,    5,    5,    5,    5],
       [   5,    5,    5,    5,    5],
       [   5,    5,    5,  672,  856],
       [   5,    5,  656,  904, 1152],
       [   5,    5,  824, 1136, 1448]])

In [42]:
f.sqrt(ff)

array([[ 2.23606798,  2.23606798,  2.23606798,  2.23606798,  2.23606798],
       [ 2.23606798,  2.23606798,  2.23606798,  2.23606798,  2.23606798],
       [ 2.23606798,  2.23606798,  2.23606798, 25.61249695, 28.70540019],
       [ 2.23606798,  2.23606798, 25.92296279, 30.06659276, 33.70459909],
       [ 2.23606798,  2.23606798, 29.25747768, 33.9411255 , 38.05259518]])

In [43]:
f.sign(ff)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [47]:
f.modf(ff)

(array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]), array([[   5.,    5.,    5.,    5.,    5.],
        [   5.,    5.,    5.,    5.,    5.],
        [   5.,    5.,    5.,  656.,  824.],
        [   5.,    5.,  672.,  904., 1136.],
        [   5.,    5.,  856., 1152., 1448.]]))

In [ ]:
f.